stop_words = {
    "a", "ada", "adalah", "agar", "akan", "akhirnya", "akibat", "aku", "amat", "antara", 
    "apa", "apakah", "apalagi", "atas", "atau", "bagai", "bagaimana", "bagi", "bahkan", 
    "bahwa", "baik", "banyak", "bawah", "beberapa", "begitu", "belakang", "beliau", 
    "belum", "benar", "berada", "berakhir", "berarti", "berasal", "berat", "berbagai", 
    "berikut", "berjalan", "bersama", "bersiap", "bersih", "besar", "betul", "bila", 
    "bisa", "bukan", "bulan", "cara", "cukup", "dalam", "dan", "dapat", "dari", "daripada", 
    "datang", "dekat", "demi", "demikian", "dengan", "depan", "di", "dia", "diantara", 
    "dianggap", "diantaranya", "diberi", "dibuat", "didapat", "digunakan", "dimana", 
    "diri", "dirinya", "disebut", "disebutkan", "diterima", "ditunjukkan", "dua", "e", 
    "hanya", "hingga", "ia", "ialah", "ibu", "itu", "jadi", "jalan", "jangan", "jarang", 
    "jauh", "jelas", "jenis", "jika", "juga", "k", "kali", "kami", "kan", "karena", "kata", 
    "ke", "kecil", "kelihatan", "keluar", "kemudian", "kemungkinan", "kepada", "kerja", 
    "keterlaluan", "kita", "kurang", "lagi", "lain", "lalu", "lama", "langsung", "lebih", 
    "lewat", "lima", "luar", "macam", "maka", "makanya", "mana", "manusia", "masih", 
    "masing", "masuk", "mau", "melalui", "melihat", "memang", "memastikan", "membuat", 
    "memiliki", "menerima", "mengadakan", "mengalami", "mengapa", "mengatakan", 
    "menggunakan", "menjadi", "menunjukkan", "menyatakan", "merasa", "mereka", 
    "merupakan", "meskipun", "mesti", "milik", "misalnya", "mungkin", "nah", "namun", 
    "nanti", "nya", "oleh", "orang", "pada", "paling", "panjang", "para", "per", 
    "pernah", "pihak", "pukul", "pun", "saat", "saja", "saling", "sama", "sambil", 
    "sampai", "sangat", "satu", "saya", "sebab", "sebagai", "sebanyak", "sebelum", 
    "sebenarnya", "sebuah", "secara", "sedang", "sedangkan", "segala", "segera", 
    "sehingga", "sejak", "sejumlah", "sekali", "sekarang", "selain", "selalu", 
    "selama", "selanjutnya", "seluruh", "semakin", "semua", "semula", "sendiri", 
    "seolah", "seperti", "sering", "serta", "sesuatu", "sesudah", "setelah", 
    "setiap", "sehingga", "siapa", "sini", "situ", "suatu", "sudah", "sungguh", 
    "supaya", "t", "tadi", "tak", "tanpa", "tapi", "telah", "tempat", "tentang", 
    "tentu", "terakhir", "terhadap", "terjadi", "termasuk", "ternyata", "tersedia", 
    "tersebut", "tertentu", "tetapi", "tidak", "tinggi", "titik", "toh", "tuan", 
    "tujuan", "umpama", "untuk", "usah", "waktu", "walau", "walaupun", "ya", 
    "yaitu", "yakin", "yang"
}
